# -*- coding: utf-8 -*-
"""Vijai Venkatesh .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCbv_2As1bRwyPwKtPUGPPCQqh5YfW1A
"""

r=float(input("Enter the radius:"))
Pi=3.14 
a=Pi*r**2
print("Area is ",a)

fn= input("Enter Filename: ")

f = fn.split(".")

print ("Extension of the file is : " + f[1])