# -*- coding: utf-8 -*-
"""Vijai Venkatesh-Fibonacci .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eY9iRL0avrppqhGCf5JdS53pnNtaIc8d
"""

n = int(input("Enter the value of 'n': "))
a = 0
b = 1
sum = 0
count = 1
print("Fibonacci Series: ", end = " ")
while(count <= n):
  print(sum, end = " ")
  count += 1
  a = b
  b = sum
  sum = a + b