# -*- coding: utf-8 -*-
"""Vijai Venkatesh .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXm01NMBaXt0kotc4rJEvyhQKKmVRO0j
"""

start=int(input("Enter the start of range:"))
end=int(input("Enter the end of range:"))
for num in range(start,end+1):
  if num>0:
    print(num, end =" ")

